# -*- coding: utf-8 -*-
"""오픈소스_텀프로젝트.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QDtquXzQXuombyuW8xKYVBrYxt_oCoAS
"""

from transformers import BlipProcessor, BlipForConditionalGeneration, BartTokenizer, BartForConditionalGeneration
from PIL import Image
from matplotlib import pyplot as plt

def generate_caption_with_blip(image_path):
    processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
    model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")
    image = Image.open(image_path)
    inputs = processor(images=image, return_tensors="pt")
    outputs = model.generate(**inputs, max_length=50, num_beams=5)
    caption = processor.decode(outputs[0], skip_special_tokens=True)
    return caption



def extend_caption_with_bart(caption):
    tokenizer = BartTokenizer.from_pretrained("facebook/bart-large-cnn")
    model = BartForConditionalGeneration.from_pretrained("facebook/bart-large-cnn")
    inputs = tokenizer(caption, return_tensors="pt", max_length=1024, truncation=True)
    outputs = model.generate(inputs["input_ids"], max_length=100, num_beams=5, repetition_penalty=1.2)
    extended_caption = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return extended_caption

def format_caption(caption):
    return caption.replace(". ", ".\n")

def main(image_path):
    caption = generate_caption_with_blip(image_path)
    print(f"Generated Caption with BLIP: {caption}")

    while True:
        user_input = input("Do you want to add more details to the description? (Y/N): ").strip().lower()
        if user_input == "n":
            plt.imshow(Image.open(image_path))
            caption = format_caption(caption)
            print("\nFinal Caption:")
            print(caption)
            break
        elif user_input == "y":
            caption = extend_caption_with_bart(caption)
            print(f"\nUpdated Caption with BART:\n{format_caption(caption)}")
        else:
            print("Invalid input. Please enter 'Y' or 'N'.")


if __name__ == "__main__":
    image_path = input("Enter the path to the image: ").strip()
    main(image_path)

